// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Sun May 12 02:13:09 2024

timer timer_inst
(
	.clock50(clock50_sig) ,	// input  clock50_sig
	.KEY0(KEY0_sig) ,	// input  KEY0_sig
	.timeOut(timeOut_sig) ,	// output  timeOut_sig
	.HEX2(HEX2_sig) ,	// output [6:0] HEX2_sig
	.HEX1(HEX1_sig) ,	// output [6:0] HEX1_sig
	.HEX0(HEX0_sig) ,	// output [6:0] HEX0_sig
	.debugTime(debugTime_sig) ,	// output [11:0] debugTime_sig
	.LEDR(LEDR_sig) 	// output [9:0] LEDR_sig
);

